const BIBLE_DATA = [
  // Ancien Testament (39 livres)
  { id: "genese", name: "Genèse", testament: "Ancien", chapters: 50 },
  { id: "exode", name: "Exode", testament: "Ancien", chapters: 40 },
  { id: "levitique", name: "Lévitique", testament: "Ancien", chapters: 27 },
  { id: "nombres", name: "Nombres", testament: "Ancien", chapters: 36 },
  { id: "deuteronome", name: "Deutéronome", testament: "Ancien", chapters: 34 },
  { id: "josue", name: "Josué", testament: "Ancien", chapters: 24 },
  { id: "juges", name: "Juges", testament: "Ancien", chapters: 21 },
  { id: "ruth", name: "Ruth", testament: "Ancien", chapters: 4 },
  { id: "1samuel", name: "1 Samuel", testament: "Ancien", chapters: 31 },
  { id: "2samuel", name: "2 Samuel", testament: "Ancien", chapters: 24 },
  { id: "1rois", name: "1 Rois", testament: "Ancien", chapters: 22 },
  { id: "2rois", name: "2 Rois", testament: "Ancien", chapters: 25 },
  { id: "1chroniques", name: "1 Chroniques", testament: "Ancien", chapters: 29 },
  { id: "2chroniques", name: "2 Chroniques", testament: "Ancien", chapters: 36 },
  { id: "esdras", name: "Esdras", testament: "Ancien", chapters: 10 },
  { id: "nehemie", name: "Néhémie", testament: "Ancien", chapters: 13 },
  { id: "esther", name: "Esther", testament: "Ancien", chapters: 10 },
  { id: "job", name: "Job", testament: "Ancien", chapters: 42 },
  { id: "psaumes", name: "Psaumes", testament: "Ancien", chapters: 150 },
  { id: "proverbes", name: "Proverbes", testament: "Ancien", chapters: 31 },
  { id: "ecclesiaste", name: "Ecclésiaste", testament: "Ancien", chapters: 12 },
  { id: "cantique", name: "Cantique des Cantiques", testament: "Ancien", chapters: 8 },
  { id: "esaie", name: "Ésaïe", testament: "Ancien", chapters: 66 },
  { id: "jeremie", name: "Jérémie", testament: "Ancien", chapters: 52 },
  { id: "lamentations", name: "Lamentations", testament: "Ancien", chapters: 5 },
  { id: "ezechiel", name: "Ézéchiel", testament: "Ancien", chapters: 48 },
  { id: "daniel", name: "Daniel", testament: "Ancien", chapters: 12 },
  { id: "osee", name: "Osée", testament: "Ancien", chapters: 14 },
  { id: "joel", name: "Joël", testament: "Ancien", chapters: 3 },
  { id: "amos", name: "Amos", testament: "Ancien", chapters: 9 },
  { id: "abdias", name: "Abdias", testament: "Ancien", chapters: 1 },
  { id: "jonas", name: "Jonas", testament: "Ancien", chapters: 4 },
  { id: "michee", name: "Michée", testament: "Ancien", chapters: 7 },
  { id: "nahum", name: "Nahum", testament: "Ancien", chapters: 3 },
  { id: "habacuc", name: "Habacuc", testament: "Ancien", chapters: 3 },
  { id: "sophonie", name: "Sophonie", testament: "Ancien", chapters: 3 },
  { id: "aggee", name: "Aggée", testament: "Ancien", chapters: 2 },
  { id: "zacharie", name: "Zacharie", testament: "Ancien", chapters: 14 },
  { id: "malachie", name: "Malachie", testament: "Ancien", chapters: 4 },

  // Nouveau Testament (27 livres)
  { id: "matthieu", name: "Matthieu", testament: "Nouveau", chapters: 28 },
  { id: "marc", name: "Marc", testament: "Nouveau", chapters: 16 },
  { id: "luc", name: "Luc", testament: "Nouveau", chapters: 24 },
  { id: "jean", name: "Jean", testament: "Nouveau", chapters: 21 },
  { id: "actes", name: "Actes", testament: "Nouveau", chapters: 28 },
  { id: "romains", name: "Romains", testament: "Nouveau", chapters: 16 },
  { id: "1corinthiens", name: "1 Corinthiens", testament: "Nouveau", chapters: 16 },
  { id: "2corinthiens", name: "2 Corinthiens", testament: "Nouveau", chapters: 13 },
  { id: "galates", name: "Galates", testament: "Nouveau", chapters: 6 },
  { id: "ephesiens", name: "Éphésiens", testament: "Nouveau", chapters: 6 },
  { id: "philippiens", name: "Philippiens", testament: "Nouveau", chapters: 4 },
  { id: "colossiens", name: "Colossiens", testament: "Nouveau", chapters: 4 },
  { id: "1thessaloniciens", name: "1 Thessaloniciens", testament: "Nouveau", chapters: 5 },
  { id: "2thessaloniciens", name: "2 Thessaloniciens", testament: "Nouveau", chapters: 3 },
  { id: "1timothee", name: "1 Timothée", testament: "Nouveau", chapters: 6 },
  { id: "2timothee", name: "2 Timothée", testament: "Nouveau", chapters: 4 },
  { id: "tite", name: "Tite", testament: "Nouveau", chapters: 3 },
  { id: "philemon", name: "Philémon", testament: "Nouveau", chapters: 1 },
  { id: "hebreux", name: "Hébreux", testament: "Nouveau", chapters: 13 },
  { id: "jacques", name: "Jacques", testament: "Nouveau", chapters: 5 },
  { id: "1pierre", name: "1 Pierre", testament: "Nouveau", chapters: 5 },
  { id: "2pierre", name: "2 Pierre", testament: "Nouveau", chapters: 3 },
  { id: "1jean", name: "1 Jean", testament: "Nouveau", chapters: 5 },
  { id: "2jean", name: "2 Jean", testament: "Nouveau", chapters: 1 },
  { id: "3jean", name: "3 Jean", testament: "Nouveau", chapters: 1 },
  { id: "jude", name: "Jude", testament: "Nouveau", chapters: 1 },
  { id: "apocalypse", name: "Apocalypse", testament: "Nouveau", chapters: 22 }
];
